In [4]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [5]:
from tensorflow import keras

In [40]:
from scipy.special import expit

In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Add a channels dimension
x_train = x_train[..., tf.newaxis].astype("float32")
x_test = x_test[..., tf.newaxis].astype("float32")


In [10]:
x=x_train[:3]

In [19]:
x.shape

(3, 28, 28, 1)

In [69]:
class dense(keras.layers.Layer):

  def __init__(self, units=32,activation='linear'):
      super(dense, self).__init__()
      self.units = units
      self.initializer={'sigmoid':keras.activations.sigmoid,'relu':keras.activations.relu,'linear':lambda x:x}
      self.activation=self.initializer.get(activation)

  def build(self, input_shape):
      self.w = self.add_weight(shape=(input_shape[-1], self.units),
                               initializer='random_normal',
                               trainable=True)
      self.b = self.add_weight(shape=(1,self.units),
                               initializer='random_normal',
                               trainable=True)

  def call(self, inputs):
      return self.activation(tf.matmul(inputs, self.w) + self.b)

In [75]:
tst=dense(units=3,activation='sigmoid')

In [76]:
tst(tf.convert_to_tensor(np.array([[1,1,1],[2,2,2.]])))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.51558757, 0.4935058 , 0.48636466],
       [0.51046854, 0.47653392, 0.47633174]], dtype=float32)>

In [77]:
tst.weights

[<tf.Variable 'dense_7/Variable:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.01119683, -0.03330211, -0.00169412],
        [-0.0084322 ,  0.03372768, -0.07433393],
        [-0.02325474, -0.06838065,  0.03583896]], dtype=float32)>,
 <tf.Variable 'dense_7/Variable:0' shape=(1, 3) dtype=float32, numpy=array([[ 0.08286058,  0.04197684, -0.01436575]], dtype=float32)>]

In [78]:
expit(np.matmul(np.array([[1,1,1],[2,2,2]]),np.array([[ 0.01119683, -0.03330211, -0.00169412],
        [-0.0084322 ,  0.03372768, -0.07433393],
        [-0.02325474, -0.06838065,  0.03583896]]))+np.array([[ 0.08286058,  0.04197684, -0.01436575]]))

array([[0.51558756, 0.49350581, 0.48636467],
       [0.51046856, 0.47653392, 0.47633172]])