In [70]:
import tensorflow as tf
import numpy as np

In [71]:
#computing dz/dx where y=x*x and z=log(y) at x=2.0 : dz/dx=2/x
x=tf.constant(2.0)
with tf.GradientTape() as g:
  g.watch(x)
  y=x*x
  z=tf.math.log(y)

print(g.gradient(z,x))



tf.Tensor(1.0, shape=(), dtype=float32)


In [72]:
#computing derivative of any arbitary function
@tf.function
def fx(x):
  y=x*x
  z=tf.math.log(y)
  return z

#print(fx(tf.constant(2.0)))

x=tf.constant(2.0)
#print(x)
with tf.GradientTape() as g:
  g.watch(x)
  y=fx(x)

print(g.gradient(y,x))

tf.Tensor(1.0, shape=(), dtype=float32)


In [73]:
#gradient of a scalar-valued differentiable function f:R^n->R is grad(f):R^n->R^n

# here f(x,y,z)=x^2*y+y^2*x+z^2
@tf.function
def fx(x):
  z=x[0]*x[0]*x[1]+x[1]*x[1]*x[0]+x[2]*x[2]
  return z

#print(fx(tf.constant([1,1,1])))

x=tf.constant([1.0,1,1])
with tf.GradientTape() as g:
  g.watch(x)
  y=fx(x)

print(g.gradient(y,x))

tf.Tensor([3. 3. 2.], shape=(3,), dtype=float32)


In [74]:
#the Jacobian matrix of a vector-valued function f:R^n->R^m is jacobian(f):R^n->R^(m x n)

# here f(x,y,z)=x^2*y+y^2*x+z^2
@tf.function
def f1(x):
  z=x[0]*x[0]*x[1]
  return z

@tf.function
def f2(x):
  z=5*x[0]+tf.math.sin(x[1])
  return z



x=tf.Variable([1.0,1])


with tf.GradientTape(persistent=True) as g:
  fn=[f1(x),f2(x)]
  #y=f1(x)
  #z=f2(x)

print(g.jacobian(fn[0],x))
print(g.jacobian(fn[1],x))

tf.Tensor([2. 1.], shape=(2,), dtype=float32)
tf.Tensor([5.        0.5403023], shape=(2,), dtype=float32)


In [77]:
np.array([g.jacobian(fn[i], x).numpy() for i in range(x.shape[0])])

array([[2.       , 1.       ],
       [5.       , 0.5403023]], dtype=float32)